# Generated by Django 5.1.3 on 2025-01-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
    ]
