# Generated by Django 5.1.3 on 2025-01-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_candidate_cv"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="cv",
        ),
    ]
